In [1]:
import numpy as np

In [20]:
x_data = np.arange(2,21,2).reshape(-1,1)
t_data = np.array([0,0,0,0,0,0,1,1,1,1]).reshape(-1,1)
x_data, t_data

(array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14],
        [16],
        [18],
        [20]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1]]))

In [21]:
W = np.random.rand(1,1)
b = np.random.rand(1)
W, b

(array([[0.75165814]]), array([0.74839454]))

In [22]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def loss_func(x, t):
    delta = 1e-7
    z = np.dot(x, W) + b
    y = sigmoid(z)
    return -np.sum(t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

In [23]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

In [24]:
def error_val(x, t):
    delta = 1e-7
    z = np.dot(x, W) + b
    y = sigmoid(z)
    return -np.sum(t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

def predict(x):
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    if y >= 0.5:
        result = 1
    else :
        result = 0
        
    return y, result

In [25]:
learning_rate = 1e-3

f = lambda x : loss_func(x_data, t_data)

print('Initial error vlaue =', error_val(x_data, t_data))
print('Initial W =', W.tolist())
print('Initial b =', b)

for step in range(100001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 10000 == 0):
        print('step =', step, end=' ')
        print('Initial error vlaue =', error_val(x_data, t_data), end=' ')
        print('Initial W =', W.tolist(), end=' ')
        print('Initial b =', b)

Initial error vlaue = 36.187615062509714
Initial W = [[0.7516581413458232]]
Initial b = [0.74839454]
step = 0 Initial error vlaue = 34.419358058614286 Initial W = [[0.7100094495377738]] Initial b = [0.74253422]
step = 10000 Initial error vlaue = 1.711730776006148 Initial W = [[0.4722432696689025]] Initial b = [-5.89274137]
step = 20000 Initial error vlaue = 1.2672965685805329 Initial W = [[0.628813279455652]] Initial b = [-7.97278553]
step = 30000 Initial error vlaue = 1.066377373114322 Initial W = [[0.7353966753044481]] Initial b = [-9.38175845]
step = 40000 Initial error vlaue = 0.9430331688285216 Initial W = [[0.8193117119649982]] Initial b = [-10.48766802]
step = 50000 Initial error vlaue = 0.8563274663603105 Initial W = [[0.889863142749873]] Initial b = [-11.41550872]
step = 60000 Initial error vlaue = 0.7904984492292426 Initial W = [[0.9514507608365811]] Initial b = [-12.22422143]
step = 70000 Initial error vlaue = 0.7379749972797566 Initial W = [[1.006537193430919]] Initial b = 

In [26]:
predict(12)

(array([[0.26489753]]), 0)

In [27]:
predict(13)

(array([[0.53123384]]), 1)

In [30]:
loaded_data = np.loadtxt('c_data.csv', delimiter=',', dtype=np.float32)
loaded_data

array([[ 2.,  4.,  0.],
       [ 4., 11.,  0.],
       [ 6.,  6.,  0.],
       [ 8.,  5.,  0.],
       [10.,  7.,  1.],
       [12., 16.,  1.],
       [14.,  8.,  1.],
       [16.,  3.,  1.],
       [18.,  7.,  1.]], dtype=float32)

In [34]:
x_data = loaded_data[:,:-1]
t_data = loaded_data[:,[-1]]
x_data.shape, t_data.shape

((9, 2), (9, 1))

In [35]:
W = np.random.rand(2,1)
b = np.random.rand(1)
W, b

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def loss_func(x, t):
    delta = 1e-7
    z = np.dot(x, W) + b
    y = sigmoid(z)
    return -np.sum(t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)
        
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

def error_val(x, t):
    delta = 1e-7
    z = np.dot(x, W) + b
    y = sigmoid(z)
    return -np.sum(t*np.log(y+delta) + (1-t)*np.log((1-y)+delta))

def predict(x):
    z = np.dot(x, W) + b
    y = sigmoid(z)
    
    if y >= 0.5:
        result = 1
    else :
        result = 0
        
    return y, result

learning_rate = 1e-3

f = lambda x : loss_func(x_data, t_data)

print('Initial error vlaue =', error_val(x_data, t_data))
print('Initial W =', W.tolist())
print('Initial b =', b)

for step in range(100001):
    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 10000 == 0):
        print('step =', step, end=' ')
        print('Initial error vlaue =', error_val(x_data, t_data), end=' ')
        print('Initial W =', W.tolist(), end=' ')
        print('Initial b =', b)

Initial error vlaue = 24.93498609620595
Initial W = [[0.731189854929079], [0.33850876437220934]]
Initial b = [0.36684485]
step = 0 Initial error vlaue = 23.857141924723276 Initial W = [[0.7112864140539636], [0.3126899056101371]] Initial b = [0.36289418]
step = 10000 Initial error vlaue = 1.4058832520827274 Initial W = [[0.5840805103528184], [-0.006247099966179226]] Initial b = [-4.88204437]
step = 20000 Initial error vlaue = 0.9763021977493552 Initial W = [[0.7531740084215048], [0.054350466862556956]] Initial b = [-6.9225614]
step = 30000 Initial error vlaue = 0.7918215903852103 Initial W = [[0.8703706208777539], [0.09405931833708281]] Initial b = [-8.27004885]
step = 40000 Initial error vlaue = 0.6820774456950298 Initial W = [[0.960794326392903], [0.12792184297147324]] Initial b = [-9.31147816]
step = 50000 Initial error vlaue = 0.6060477072114384 Initial W = [[1.0344457680175774], [0.15995588028958652]] Initial b = [-10.17900995]
step = 60000 Initial error vlaue = 0.5486325640831304 

In [36]:
predict([3,17])

(array([0.01520432]), 0)

In [44]:
predict([1,30])

(array([0.0643112]), 0)