In [1]:
import numpy as np

In [8]:
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)
print(array1.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [6]:
array2 = np.array([[1,2,3],
                   [2,3,4]])
print(type(array2))
print(array2.shape)
print(array2.ndim)

<class 'numpy.ndarray'>
(2, 3)
2


In [9]:
array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)
print(array3.ndim)

<class 'numpy.ndarray'>
(1, 3)
2


In [10]:
array4 = np.array([[[1,2,3]]])
print(type(array4))
print(array4.shape)
print(array4.ndim)

<class 'numpy.ndarray'>
(1, 1, 3)
3


In [11]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [13]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [15]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [18]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape, sequence_array.ndim)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,) 1


In [19]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape, one_array.ndim)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2) 2


In [21]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,1)
print(array2.shape)

array3 = array1.reshape(5,-1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
(10, 1)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d.tolist())

array5 = array3d.reshape(-1,1)
print(array5.tolist())

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]]


In [31]:
array1 = np.arange(1,10)
print(array1)

value = array1[2]
print('value:',value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [33]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

array4 = array1[3:]
print(array4)

array5 = array1[:]
print(array5)

[1 2 3]
<class 'numpy.ndarray'>
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [39]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])
print(array2d[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [43]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0,1], 2]
print(array3.tolist())

array4 = array2d[[0,2], :2]
print(array4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1 2]
 [7 8]]


In [44]:
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
array3

array([6, 7, 8, 9])

In [45]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [46]:
array2d > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
array2 = array2d[array2d > 5]
array2

array([6, 7, 8, 9])

In [50]:
org_array = np.array([3,1,9,5])
np.max(org_array)

9

In [51]:
np.argmax(org_array)

2

In [55]:
org_array = np.array([3,1,9,5])
org_array

array([3, 1, 9, 5])

In [56]:
sort_array1 = np.sort(org_array)
sort_array1

array([1, 3, 5, 9])

In [57]:
sort_array2 = org_array.sort()
sort_array2

In [58]:
org_array

array([1, 3, 5, 9])

In [59]:
sort_array1_desc = np.sort(org_array)[::-1]
sort_array1_desc

array([9, 5, 3, 1])

In [65]:
array2d = np.array([[8,12],
                    [7,1],
                    [5,6]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 5  1]
 [ 7  6]
 [ 8 12]]
[[ 8 12]
 [ 1  7]
 [ 5  6]]


In [66]:
np.max(array2d, axis=0)

array([ 8, 12])

In [67]:
np.max(array2d, axis=1)

array([12,  7,  6])

In [71]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_score_array = np.argsort(score_array)[::-1]
name_array[sort_score_array]

array(['Kate', 'Mike', 'Samuel', 'Sarah', 'John'], dtype='<U6')

In [73]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [74]:
A @ B

array([[ 58,  64],
       [139, 154]])

In [75]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
a = np.array([[1,2],[3,4]])
b =5

In [78]:
a+b

array([[6, 7],
       [8, 9]])

In [79]:
c = np.array([[1,2],[3,4]])
d = np.array([4,5])
c+d

array([[5, 7],
       [7, 9]])

In [80]:
c = np.array([[1,2],[3,4]])
d = np.array([[4],[5]])
c+d

array([[5, 6],
       [8, 9]])

In [96]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [97]:
a.shape

(2, 4)

In [103]:
iter1 = np.nditer(a, flags=['multi_index'], op_flags=['readwrite'])
iter1

In [104]:
while not iter1.finished:
    idx = iter1.multi_index
    print(a[idx])
    iter1.iternext()

10
20
30
40
50
60
70
80


# Concatenate
    블라블라블라

In [105]:
a = np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [106]:
a.shape

(2, 3)

In [108]:
row_add = np.array([70,80,90]).reshape(1,3)
col_add = np.array([1000,2000]).reshape(2,1)

In [109]:
b = np.concatenate((a, row_add), axis=0)
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [110]:
c = np.concatenate((a, col_add), axis=1)
c

array([[  10,   20,   30, 1000],
       [  40,   50,   60, 2000]])

In [111]:
def numerical_deruvative(f, x):
    delta_x = 1e-4
    return (f(x+delta_x) - f(x-delta_x)) / (2*delta_x)

In [112]:
def function1(x):
    return x**2

In [113]:
result = numerical_deruvative(function1, 3)
result

6.000000000012662

In [120]:
def my_func2(x):
    return 3*x*(np.exp(x))

In [121]:
result = numerical_deruvative(my_func2, 2)
result

66.50150507518049

In [130]:
def numerical_deruvative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print('debug 1. initial input variable =', x)
    print('debug 2. initial grad =', grad)
    print('=======================================')
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print('debug 3. idx =', idx, ', x[idx] =', x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print('debug 4. grad[idx] =', grad[idx])
        print('debu g 5. grad =', grad)
        print('====================================')
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

In [129]:
def func1(x):
    return x**2

numerical_deruvative(func1, np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx = (0,) , x[idx] = 3.0
debug 4. grad[idx] = 6.000000000012662
debug 5. grad = [6.]


array([6.])

In [131]:
def func1(val):
    x = val[0]
    y = val[1]
    return 2*x + 3*x*y + y**3

numerical_deruvative(func1, np.array([1., 2.]))

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx = (0,) , x[idx] = 1.0
debug 4. grad[idx] = 7.999999999990237
debug 5. grad = [8. 0.]
debug 3. idx = (1,) , x[idx] = 2.0
debug 4. grad[idx] = 15.000000010019221
debug 5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [132]:
def func1(val):
    w = val[0,0]
    x = val[0,1]
    y = val[1,0]
    z = val[1,1]
    
    return w*x + x*y*z + 3*w + z*y**2

numerical_deruvative(func1, np.array([[1.,2.],[3.,4.]]))

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx = (0, 0) , x[idx] = 1.0
debug 4. grad[idx] = 5.000000000023874
debug 5. grad = [[5. 0.]
 [0. 0.]]
debug 3. idx = (0, 1) , x[idx] = 2.0
debug 4. grad[idx] = 13.00000000000523
debug 5. grad = [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx = (1, 0) , x[idx] = 3.0
debug 4. grad[idx] = 32.00000000006753
debug 5. grad = [[ 5. 13.]
 [32.  0.]]
debug 3. idx = (1, 1) , x[idx] = 4.0
debug 4. grad[idx] = 15.000000000000568
debug 5. grad = [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])